version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: yourpassword
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    networks:
      - app_network

volumes:
  arangodb_data:
  arangodb_apps:

networks:
  app_network:
    driver: bridge
