[tool.poetry]
name = "mabos-standalone"
version = "0.1.0"
description = ""
authors = ["Kingler Bercy <kingler@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
