component: knowledge_models
description: Contains models for knowledge representation and management in MABOS
main-technologies:
  - Python
  - Pydantic
  - OWL
conventions:
  - Use Pydantic for data validation and serialization
  - Align models with ontology structures
  - Implement clear interfaces for knowledge operations
key-responsibilities:
  - Defining data structures for knowledge representation
  - Ensuring data integrity and validation for knowledge entities
  - Facilitating knowledge querying and manipulation
  - Providing a consistent interface for working with knowledge-related information
  - Supporting various knowledge representation paradigms
development-guidelines:
  - Use Pydantic models for data validation and serialization
  - Align model structures with corresponding ontology concepts
  - Implement clear methods for knowledge operations (e.g., querying, updating)
  - Use type hints and docstrings for better code readability
model-implementation:
  - Clearly define the model's purpose and its role in knowledge representation
  - Consider relationships with other knowledge models and ontology structures
  - Implement appropriate data validation rules
  - Ensure consistency with established knowledge representation standards