component: ontology
description: Contains ontology definitions, management tools, and related utilities for MABOS
main-technologies:
  - Python
  - OWL
  - RDF
conventions:
  - Use standard ontology formats (OWL, RDF)
  - Implement clear interfaces for ontology querying and updates
  - Maintain versioning for ontology changes
key-responsibilities:
  - Defining and managing ontologies for various domains within MABOS
  - Providing tools for ontology creation, modification, and querying
  - Enabling knowledge representation and reasoning based on ontological structures
  - Facilitating natural language interactions with the knowledge base
development-guidelines:
  - Use standard ontology formats (OWL, RDF) for compatibility
  - Implement clear interfaces for ontology querying and updates
  - Maintain versioning for ontology changes to track evolution
  - Ensure consistency between ontology definitions and system implementations
ontology-management:
  - Clearly define concepts, relationships, and axioms
  - Use established ontology design patterns where applicable
  - Implement tools for ontology validation and consistency checking
  - Consider performance implications for large-scale ontologies
ontology-integration:
  - Develop clear interfaces for other system components to interact with ontologies
  - Implement caching mechanisms for frequently accessed ontology data
  - Consider using a triplestore or graph database for efficient storage and querying
testing-ontologies:
  - Implement unit tests for ontology management functions
  - Create tests for ontology consistency and logical inference
  - Develop integration tests to verify ontology usage in the broader system context