component: system_models
description: Contains system-wide models and structures for MABOS
main-technologies:
  - Python
  - Pydantic
conventions:
  - Use Pydantic for data validation and serialization
  - Implement clear interfaces for system-wide operations
  - Ensure consistency with other model components
key-responsibilities:
  - Defining core system-wide data structures
  - Ensuring data integrity and validation for system properties
  - Facilitating system-wide operations and interactions
  - Providing a consistent interface for working with system-level information
  - Supporting the integration of various system components
development-guidelines:
  - Use Pydantic models for data validation and serialization
  - Implement clear interfaces for system-wide operations and interactions
  - Ensure consistency with other model components (agent, business, MDD)
  - Use type hints and docstrings for better code readability
model-implementation:
  - Clearly define the model's purpose and its role in the overall system architecture
  - Consider interactions with other system components and models
  - Implement appropriate data validation rules
  - Ensure scalability and performance for system-wide use