import os
import yaml
from typing import List
import uuid
from core.models.agent.goal import Goal
from core.tools.llm_manager import LLMManager

class LLMDecomposer:
    def __init__(self, api_key=None):
        config_path = os.path.join(os.path.dirname(__file__), '..', 'llm_config.yaml')
        with open(config_path, 'r') as config_file:
            self.config = yaml.safe_load(config_file)
        self.llm_manager = LLMManager(self.config['llms'], api_key)

    def decompose(self, goal: Goal) -> List[Goal]:
        """
        Decompose a high-level goal into 3-5 specific, actionable subgoals using a Large Language Model (LLM).

        Args:
            goal (Goal): The high-level goal to be decomposed.

        Returns:
            List[Goal]: A list of subgoals generated by the LLM.
        """
        prompt = self._create_prompt(goal)
        response = self.llm_manager.get_text_completion(prompt)
        subgoals = self._parse_response(response, goal.priority)
        return subgoals

    def _create_prompt(self, goal: Goal) -> str:
        return f"""
        Given the following high-level goal:
        
        "{goal.description}"
        
        Please decompose this goal into 3-5 specific, actionable subgoals. Each subgoal should be a clear, concise step towards achieving the main goal. Format your response as a numbered list, with each subgoal on a new line.
        
        For example:
        1. [Subgoal 1 description]
        2. [Subgoal 2 description]
        3. [Subgoal 3 description]
        ...
        
        Please provide the subgoals now:
        """

    def _parse_response(self, response: str, parent_priority: int) -> List[Goal]:
        subgoals = []
        lines = response.split('\n')
        for line in lines:
            if line.strip() and line[0].isdigit():
                description = line.split('.', 1)[1].strip()
                subgoal = Goal(
                    id=str(uuid.uuid4()),
                    description=description,
                    priority=max(1, parent_priority - 1),
                    llm_generated_context="Generated as a subgoal by LLMDecomposer"
                )
                subgoals.append(subgoal)
        return subgoals

    def validate_subgoals(self, main_goal: Goal, subgoals: List[Goal]) -> List[Goal]:
        subgoal_descriptions = "\n".join([f"{i+1}. {sg.description}" for i, sg in enumerate(subgoals)])
        validation_prompt = f"""
        Main Goal: {main_goal.description}
        
        Subgoals:
        {subgoal_descriptions}
        
        Please validate these subgoals. Ensure they are:
        1. Relevant to the main goal
        2. Specific and actionable
        3. Collectively comprehensive in achieving the main goal
        
        If any subgoals do not meet these criteria, please suggest improvements or replacements. 
        If all subgoals are valid, simply respond with "All subgoals are valid."
        
        Your response:
        """

        validation_response = self.llm_manager.get_text_completion(validation_prompt)

        if "All subgoals are valid" in validation_response:
            return subgoals
        else:
            for subgoal in subgoals:
                subgoal.llm_generated_context += f"\nValidation feedback: {validation_response}"
            return subgoals

    def decompose_with_validation(self, goal: Goal) -> List[Goal]:
        initial_subgoals = self.decompose(goal)
        validated_subgoals = self.validate_subgoals(goal, initial_subgoals)
        return validated_subgoals