component: reasoning_models
description: Contains models and structures for reasoning capabilities in MABOS
main-technologies:
  - Python
  - Pydantic
  - Custom reasoning framework
conventions:
  - Use Pydantic for data validation and serialization
  - Implement clear interfaces for reasoning operations
  - Align with ontology and knowledge representation standards
key-responsibilities:
  - Defining data structures for reasoning-related concepts
  - Ensuring data integrity and validation for reasoning properties
  - Facilitating the execution of reasoning and inference processes
  - Providing a consistent interface for working with reasoning-related information
  - Supporting various reasoning paradigms (e.g., rule-based, temporal)
development-guidelines:
  - Use Pydantic models for data validation and serialization
  - Implement clear interfaces for reasoning operations and rule definitions
  - Align reasoning models with ontology and knowledge representation standards
  - Use type hints and docstrings for better code readability
model-implementation:
  - Clearly define the model's purpose and its role in the reasoning process
  - Consider interactions with other knowledge and reasoning components
  - Implement appropriate data validation rules
  - Ensure consistency with ontology and knowledge base structures
  