component: agent_models
description: Contains data models and structures specific to agents in the MABOS system
main-technologies:
  - Python
  - Pydantic
conventions:
  - Use Pydantic for data validation and serialization
  - Keep models focused on data representation
  - Use clear naming conventions for agent-related models
key-responsibilities:
  - Defining data structures for agent-related concepts
  - Ensuring data integrity and validation for agent properties
  - Facilitating serialization and deserialization of agent data
  - Providing a consistent interface for working with agent-related information
development-guidelines:
  - Use Pydantic models for data validation and serialization
  - Keep models focused on data representation, moving logic to services
  - Use clear and consistent naming conventions for models and their fields
  - Implement validation rules using Pydantic field validators where necessary
model-implementation:
  - Clearly define the model's purpose and its place in the agent architecture
  - Consider relationships with other agent models
  - Implement appropriate data validation rules
  - Use type hints and docstrings for better code readability